-- ===============================================
-- 🔥 ERP Database Schema (Firebird SQL)
-- ===============================================

-- Najpierw usuwamy wszystko, jeśli istnieje (bez błędów jeśli nie istnieje)
-- Kolejność ma znaczenie z powodu zależności FK

-- ===============================================
-- 👥 SYS_USER – użytkownicy systemu
-- ===============================================
CREATE TABLE SYS_USER (
    USER_ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    NAME VARCHAR(100),
    SURNAME VARCHAR(100),
    EMAIL VARCHAR(100),
    ROLE VARCHAR(50) CHECK (ROLE IN ('ADMIN', 'SALES', 'ACCOUNTANT', 'WAREHOUSE')),
    ACTIVE SMALLINT DEFAULT 1
);

-- ===============================================
-- 🧍 CUSTOMER – klienci
-- ===============================================
CREATE TABLE CUSTOMER (
    CUSTOMER_ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100),
    PHONE VARCHAR(50),
    ADDRESS VARCHAR(255),
    CITY VARCHAR(100),
    COUNTRY VARCHAR(100)
);

-- ===============================================
-- 📦 PRODUCT – produkty
-- ===============================================
CREATE TABLE PRODUCT (
    PRODUCT_ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(255),
    PRICE DECIMAL(10,2) NOT NULL,
    STOCK_QUANTITY INTEGER DEFAULT 0
);

-- ===============================================
-- 🧾 CUSTOMER_ORDER – zamówienia klientów
-- ===============================================
CREATE TABLE CUSTOMER_ORDER (
    ORDER_ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CUSTOMER_ID INTEGER NOT NULL,
    ORDER_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    STATUS VARCHAR(50) DEFAULT 'PENDING',
    TOTAL_AMOUNT DECIMAL(10,2) NOT NULL,
    CONSTRAINT FK_ORDER_CUSTOMER FOREIGN KEY (CUSTOMER_ID)
        REFERENCES CUSTOMER (CUSTOMER_ID)
);

-- ===============================================
-- 🧩 ORDER_ITEM – pozycje zamówień
-- ===============================================
CREATE TABLE ORDER_ITEM (
    ORDER_ITEM_ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ORDER_ID INTEGER NOT NULL,
    PRODUCT_ID INTEGER NOT NULL,
    QUANTITY INTEGER NOT NULL,
    UNIT_PRICE DECIMAL(10,2) NOT NULL,
    CONSTRAINT FK_ORDERITEM_ORDER FOREIGN KEY (ORDER_ID)
        REFERENCES CUSTOMER_ORDER (ORDER_ID),
    CONSTRAINT FK_ORDERITEM_PRODUCT FOREIGN KEY (PRODUCT_ID)
        REFERENCES PRODUCT (PRODUCT_ID)
);

-- ===============================================
-- 🧾 INVOICE – faktury
-- ===============================================
CREATE TABLE INVOICE (
    INVOICE_ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    INVOICE_NUMBER VARCHAR(50) NOT NULL UNIQUE,
    CUSTOMER_ID INTEGER NOT NULL,
    ORDER_ID INTEGER,
    ISSUE_DATE DATE NOT NULL,
    DUE_DATE DATE NOT NULL,
    TOTAL_AMOUNT DECIMAL(10,2) NOT NULL,
    STATUS VARCHAR(50) DEFAULT 'UNPAID',
    CREATED_BY INTEGER,
    CONSTRAINT FK_INVOICE_CUSTOMER FOREIGN KEY (CUSTOMER_ID)
        REFERENCES CUSTOMER (CUSTOMER_ID),
    CONSTRAINT FK_INVOICE_ORDER FOREIGN KEY (ORDER_ID)
        REFERENCES CUSTOMER_ORDER (ORDER_ID),
    CONSTRAINT FK_INVOICE_USER FOREIGN KEY (CREATED_BY)
        REFERENCES SYS_USER (USER_ID)
);

-- ===============================================
-- 💰 PAYMENT – płatności
-- ===============================================
CREATE TABLE PAYMENT (
    PAYMENT_ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    INVOICE_ID INTEGER NOT NULL,
    PAYMENT_DATE DATE NOT NULL,
    AMOUNT DECIMAL(10,2) NOT NULL,
    METHOD VARCHAR(50),
    CONFIRMED SMALLINT DEFAULT 0,
    CONSTRAINT FK_PAYMENT_INVOICE FOREIGN KEY (INVOICE_ID)
        REFERENCES INVOICE (INVOICE_ID)
);

-- ===============================================
-- ✅ Indeksy dodatkowe (jeśli chcesz wydajności)
-- ===============================================
CREATE INDEX IDX_ORDER_CUSTOMER ON CUSTOMER_ORDER (CUSTOMER_ID);
CREATE INDEX IDX_ORDERITEM_ORDER ON ORDER_ITEM (ORDER_ID);
CREATE INDEX IDX_ORDERITEM_PRODUCT ON ORDER_ITEM (PRODUCT_ID);
CREATE INDEX IDX_INVOICE_CUSTOMER ON INVOICE (CUSTOMER_ID);
CREATE INDEX IDX_PAYMENT_INVOICE ON PAYMENT (INVOICE_ID);

-- ===============================================
-- 💬 Gotowe!
-- ===============================================
COMMIT;


